### ISSUE TITLE
Increased Tauren CombatReach doesnt get restored after being polymorphed

### ISSUE THREAD

**Issue by Klimpb** [Aeded/BCC_Buglist#60]
**Current behaviour:**
Currently Hitboxes/Combatreach are normalized while in arena.
[https://imgur.com/a/U1DMQtl](https://imgur.com/a/U1DMQtl)

**Expected behaviour:**
They should not be normalized, taurens should have a larger hitbox.

**Proof for expected behavior:**
[https://www.youtube.com/watch?v=zANeJ_lCSXc](https://www.youtube.com/watch?v=zANeJ_lCSXc) (video released in 2.4.2 or 2.4.3 on warcraftmovies)

**Comment by Klimpb** [comment]
I wrote down my thoughts about this a few months:


**Combat Reach/Tauren hitbox** 

**Pros**

- Many who rolled tauren in Classic did so with this mechanic in mind
- A faction balancing factor for druids, it being mostly negative from a tauren druid’s pov but which evens out the playing field of the racials between a night elf and a tauren druid.
- More race variance for horde warriors and enh shamans(no clear cut “best pvp race”)
- Increases skill cap because of different spell ranges to keep in mind in terms of dead-zoning warriors, but also anticipating maximum range of enemy spells.

**Cons**

- Can feel strange/bugged(gets amplified in a tauren vs tauren scenario).
- Tilting to be hit by melee from a further than anticipated distance.
- The larger hitbox, in combination with the melee leeway mechanic synergizes well with the size of objects in the arena maps(being able to auto-attack through some pillars etc).
- Will cause tauren druids to have only positives from their racial and no negatives, making them more superior to night elf than they otherwise would have been.
- Will make tauren hunter the best hunter race for horde

**Comment by WOTLKwaitingROOM** [comment]
Here's a different perspective on the above Pros/Cons.

**Pros**

> 1. Many who rolled tauren in Classic did so with this mechanic in mind

Only people who knew about this mechanic and planned on using it and who somewhat care and are invested in arena which is already a tiny subset of people (translates to roughly you and your friends).

> 2. A faction balancing factor for druids, it being mostly negative from a tauren druid’s pov but which evens out the playing field of the racials between a night elf and a tauren druid.

Shapeshift forms are already normalized or even smaller than default, this bigger hitbox also increased the reach of War Stomp so is that really negative?

> 3. More race variance for horde warriors and enh shamans(no clear cut “best pvp race”)

How's Orc still not the best pvp race and the best race overall for those classes even with dynamic hitboxes? 
I get it, you personally like hitting people through pillars and stopping drinks and restealths but Orc is still objectively better overall.

> 4. Increases skill cap because of different spell ranges to keep in mind in terms of dead-zoning warriors, but also anticipating maximum range of enemy spells.

Putting spikes on a soccer field also increases the skill cap, not an argument.

**Cons**

> 1. Can feel strange/bugged(gets amplified in a tauren vs tauren scenario).

Agreed, it can also be confusing to people not in the know (the vast majority of players), same as:

> 2. Tilting to be hit by melee from a further than anticipated distance.

> 3. The larger hitbox, in combination with the melee leeway mechanic synergizes well with the size of objects in the arena maps(being able to auto-attack through some pillars etc).

So far it seems like every single pillar, the tomb on Ruins of Lordaeron, and even the bridge on Blade's Edge Arena (if the Tauren player jumps), not really "...some pillars", eh?

> 4. Will cause tauren druids to have only positives from their racial and no negatives, making them more superior to night elf than they otherwise would have been.

War Stomp range was affected by this in my tests early in the Beta, meaning it will be smaller now so that's already a small downside.
Besides, players tend to choose factions because of other reasons such as synergizing with their partners' racials, unless you're trying to make it out to be as if people would suddenly only play Warrior/Druid on Horde which is bollocks, or whatever their friends are playing.

> 5. Will make tauren hunter the best hunter race for horde

That's just completely made up, but even if true - so what? 
Is there some law saying "Orc must be the best hunter race on Horde"? That's up to the players, their preferences as well as game understanding.

**Summary**:
I hope Blizzard sticks to normalized hitboxes, I believe this was a left-in RPG element which makes sense for its time and what the game was to its players at the time. 
Given that arenas are supposed to be a competitive environment, or are treated as such, it only makes sense for such small changes to be made in favour of reinforcing that.
The above thoughts coming from @Klimpb come from an extremely biased point of view of a player constantly looking to take advantage of such small quirks which have not much to do with actual gameplay.
It seems that the Classic player-base is now in favour of #somechanges and I believe most of the die-hard arena players would also be in favour of this change.

**Comment by Klimpb** [comment]
> Here's a different perspective on the above Pros/Cons.
> 
> **Pros**
> 
> > 1. Many who rolled tauren in Classic did so with this mechanic in mind
> 
> Only people who knew about this mechanic and planned on using it and who somewhat care and are invested in arena which is already a tiny subset of people (translates to roughly you and your friends).
> 
> > 1. A faction balancing factor for druids, it being mostly negative from a tauren druid’s pov but which evens out the playing field of the racials between a night elf and a tauren druid.
> 
> Shapeshift forms are already normalized or even smaller than default, this bigger hitbox also increased the reach of War Stomp so is that really negative?
> 
> > 1. More race variance for horde warriors and enh shamans(no clear cut “best pvp race”)
> 
> How's Orc still not the best pvp race and the best race overall for those classes even with dynamic hitboxes?
> I get it, you personally like hitting people through pillars and stopping drinks and restealths but Orc is still objectively better overall.
> 
> > 1. Increases skill cap because of different spell ranges to keep in mind in terms of dead-zoning warriors, but also anticipating maximum range of enemy spells.
> 
> Putting spikes on a soccer field also increases the skill cap, not an argument.
> 
> **Cons**
> 
> > 1. Can feel strange/bugged(gets amplified in a tauren vs tauren scenario).
> 
> Agreed, it can also be confusing to people not in the know (the vast majority of players), same as:
> 
> > 1. Tilting to be hit by melee from a further than anticipated distance.
> 
> > 1. The larger hitbox, in combination with the melee leeway mechanic synergizes well with the size of objects in the arena maps(being able to auto-attack through some pillars etc).
> 
> So far it seems like every single pillar, the tomb on Ruins of Lordaeron, and even the bridge on Blade's Edge Arena (if the Tauren player jumps), not really "...some pillars", eh?
> 
> > 1. Will cause tauren druids to have only positives from their racial and no negatives, making them more superior to night elf than they otherwise would have been.
> 
> War Stomp range was affected by this in my tests early in the Beta, meaning it will be smaller now so that's already a small downside.
> Besides, players tend to choose factions because of other reasons such as synergizing with their partners' racials, unless you're trying to make it out to be as if people would suddenly only play Warrior/Druid on Horde which is bollocks, or whatever their friends are playing.
> 
> > 1. Will make tauren hunter the best hunter race for horde
> 
> That's just completely made up, but even if true - so what?
> Is there some law saying "Orc must be the best hunter race on Horde"? That's up to the players, their preferences as well as game understanding.
> 
> **Summary**:
> I hope Blizzard sticks to normalized hitboxes, I believe this was a left-in RPG element which makes sense for its time and what the game was to its players at the time.
> Given that arenas are supposed to be a competitive environment, or are treated as such, it only makes sense for such small changes to be made in favour of reinforcing that.
> The above thoughts coming from @Klimpb come from an extremely biased point of view of a player constantly looking to take advantage of such small quirks which have not much to do with actual gameplay.
> It seems that the Classic player-base is now in favour of #somechanges and I believe most of the die-hard arena players would also be in favour of this change.

Fair points, albeit a bit hostile mr anonymous stranger.
I just think it's odd to apply such drastic changes specifically for arenas and then only for this one single mechanic, while there are many other similar TBC quirks that are left untouched.
