### ISSUE TITLE
Lightning overload and Chain Lightning proc chance

### ISSUE THREAD

**Issue by Aeded** [Aeded/BCC_Buglist#88]
**Current behaviour:**
Currently proc chance of 5/5 Lightning Overload seems to be way off 20%.
I did 223 Chain Lightnings on Boss Dummy (1 target) and got 21 Overloads.  Thats less than 10% proc chance

![image](https://user-images.githubusercontent.com/45561230/117579105-c0039800-b0f1-11eb-903c-c7dfb2a0acd4.png)

**Expected behaviour:**
Chain Lightning should have 20% chance to proc Lightning Overload as advertised on tooltip.
When tested with Lightning bolt, it seemed to work fine and I was getting around 20% proc chance.

**Comment by Aggrend** [comment]
This is not a bug. The very abridged reason is that there is a 1/3 chance when it procs, because it can hit up to 3 targets and each target makes the check on the proc independently. Its not great if you don't hit 3 targets, but if you hit 3 targets it could concievably proc against all three which ends up being more than double damage for the attack if it does occur. Kinda quirky and unintuitive, but it's authentic.

Thanks for the report though!

**Comment by Aeded** [comment]
Thanks again for taking the time and looking into it ❤️
